# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: postgresql
  database: dispensary_dev

test: &test
  adapter: postgresql
  database: dispensary_test

production:
  adapter: postgresql
  database: dispensary_prod

cucumber:
  <<: *test
